#!/usr/bin/env bash
export PS4='[\D{%H:%M:%S}] ${BASH_SOURCE##*/}:${LINENO}> '
set -xeuo pipefail

echo "[hook] running disk-image build before push…"
bash src/docker/run_in_docker.sh

echo "[hook] pre-push hook succeeded – pushing allowed."
